### ISSUE TITLE
Build error ?

### ISSUE THREAD

**Issue by ThanhByKyTa** [Vauff/MapDownloader#1]
![image](https://user-images.githubusercontent.com/33537916/53582884-fb6db800-3bb2-11e9-8d84-8d27bf968f3b.png)

**Comment by Vauff** [comment]
This is more of a workspace setup issue than a program issue, but I'll still try to help regardless.

Does that folder path exist? And does the EXE exist at that location? 

Also in Visual Studio, check that "Assembly name" and "Output path" look like this under Project > MapDownloader Properties... (Application and Build tabs)

![](https://i.imgur.com/ySbwvy7.png)
![](https://i.imgur.com/yyEFr8P.png)
