### ISSUE TITLE
How to open the file?

### ISSUE THREAD

**Issue by petar467** [Vauff/MapDownloader#2]
Hey! I just downloaded ur file but idk how and where i need to open it.... thanks forwards

**Comment by Vauff** [comment]
For Windows, you should be able to just run the EXE file normally by double clicking on it like you usually do.

For Mac/Linux, run the EXE in wine via `wine MapDownloader.exe` in terminal.

**Comment by petar467** [comment]
![Unbenannt](https://user-images.githubusercontent.com/62113702/76550812-01b79500-6493-11ea-9cf1-be4f126b4c89.PNG)


no look at those files hahaha

**Comment by PolarizedIons** [comment]
You likely want the runnable file, not the source code ;) You can find the exe file here: https://github.com/Vauff/MapDownloader/releases

**Comment by petar467** [comment]
Oh okey.... sorry hahah, u have discord? i have a few questions

**Comment by petar467** [comment]
I have alle zombie maps now - it works but the zombies are error blocks.... what can i do?

**Comment by Vauff** [comment]
Ideally you should fix your ingame downloads and figure out why you can't connect to the FastDL. Make sure you don't have FACEIT anti-cheat running.

Otherwise, you can manually download the server resources [here](https://gflclan.com/forums/topic/51114-server-resources-pack/).

**Comment by petar467** [comment]
how can i figure it out and turn faceit off?
